# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(14151A)
$foreground = rgb(CFE2FC)
$color0 = rgb(3B3C42)
$color1 = rgb(11254F)
$color2 = rgb(112652)
$color3 = rgb(162C58)
$color4 = rgb(423E5C)
$color5 = rgb(39598B)
$color6 = rgb(5980B8)
$color7 = rgb(B2CDF2)
$color8 = rgb(7D8FA9)
$color9 = rgb(163169)
$color10 = rgb(17336D)
$color11 = rgb(1D3A75)
$color12 = rgb(58527B)
$color13 = rgb(4C76B9)
$color14 = rgb(76ABF5)
$color15 = rgb(B2CDF2)
